global using Log = LabApi.Features.Console.Logger;
global using LabApi.Loader.Features.Plugins;
global using LabApi.Features;
global using System;
global using MEC;
global using S.C.G = System.Collections.Generic;
global using LabApi.Features.Wrappers;
global using PlayerRoles;
global using CommandSystem;
global using LAPI.F.P = LabApi.Features.Permissions;
global using Ligindary.Extensions;
global using Mirror;
global using NetMsg = PlayerRoles.FirstPersonControl.NetworkMessages;
global using System.Text;
global using Ligindary.Commands.Appearance;
global using LabApi.Events.Arguments.PlayerEvents;
global using LabApi.Events.Handlers;
global using System.Reflection;
global using HSM.C.M.H = HintServiceMeow.Core.Models.Hints;
global using HSM.C.U = HintServiceMeow.Core.Utilities;
global using Ligindary.Wrappers;
global using Footprinting;
global using Ligindary.API.Interfaces;
global using Utils;
global using CPE = CustomPlayerEffects;

namespace Ligindary.Usings;
